plugins {
    id 'java'
    id 'application'
}

group = 'com.incidentmanagement'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'com.incidentmanagement.IncidentManagementApplication'
}

tasks.named('test') {
    useJUnitPlatform()
}
